### ISSUE TITLE
Trigger only a subset of actions

### ISSUE THREAD

**Issue by BraunTom** [hpi-swa-teaching/Actions#20]
Sometimes you do not want to be able to trigger the whole range of shortcuts. An example would be a PasteUpMorph. It has some actions defined in filterEvent:for: and some in keystrokeInWorld: that is triggered from keyStroke:

**Comment by BraunTom** [comment]
Therefore it should be necessary to differentiate between groups and a set of shortcuts (as you possibly want to have multiple menus too)

**Comment by WilliamBrandt** [comment]
As a user of the shortcut tool i want to be able to trigger different groups of sets of shortcuts, which are specified in the shortcut browser, depending on my current mouse-focus even within Objects e.g. by having different groups for sub-objects in order to make the shortcuts even individualizable more fitting to the environment they get executed in.

Time: 90

**Comment by Tonybodo** [comment]
resolved during sprint 4
